/* This file was generated by syncqt. */
#ifndef QT_QT3DINPUT_VERSION_H
#define QT_QT3DINPUT_VERSION_H

#define QT3DINPUT_VERSION_STR "5.15.0"

#define QT3DINPUT_VERSION 0x050F00

#endif // QT_QT3DINPUT_VERSION_H
